#Docker compose file for building the DockerFile and
# and mounting the volumes
version: '3'
services: 
  nginx:
    build: .
    ports:
      # - "80:8080"
      - "80:80"
    # volumes: 
      # - ~/cert:/etc/cert